# Извлечено из дампа 2018-11-17_02-10_db_idrp.sql, таблица articlex, как есть
id: 45
url: "pritchi"
type: 2
pg_ttl: "Любовь выше поста. Притча о любви"
pg_dsc: "Любовь выше поста. Притча о любви"
anons: ""
dt1_day: 0
dt1_month: 0
dt2_day: 0
dt2_month: 0
dt3_day: 0
dt3_month: 0
days_easter: null
last_date: "2011-06-25 11:15:37"
